# # config/database.yml

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   username: postgres
#   password: password
#   host: localhost
#   pool: 5

# development:
#   <<: *default
#   database: postgres

# test:
#   <<: *default
#   database: test_postgres

# production:
#   <<: *default
#   database: your_app_name_production

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
